language: python
python:
  - "3.4"
before_install:
  - sudo apt-add-repository ppa:kivy-team/kivy
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-kivy
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  # start a headless X
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - python setup.py dev
# command to run tests
script: "python setup.py test"
