language: python
python:
  - "3.2"
before_install:
  - sudo apt-get update -qq
  # sudo apt-get install -qq libreoffice unoconv tidy
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# command to install dependencies
install:
  - python setup.py dev
# command to run tests
script: "python setup.py test"
