---
- hosts: all
  become: yes
  remote_user: root
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Aptitude safe-upgrade
    apt: upgrade=safe

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    with_items:
      - python-pip
      - build-essential
      - git
      - python
      - python-dev
      - libav-tools
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - zlib1g-dev

  - name: Upgrade pip, virtualenv, setuptools
    pip:
      name={{ item }}
      state=latest
    with_items:
      - pip
      - virtualenv
      - setuptools

  - name: Create virtualenv
    become: no
    command: virtualenv /home/vagrant/venv27 -p python2.7
    args:
      creates: /home/vagrant/venv27
