---
# this playbook installs kivy in a local virtualenv.
- hosts: all
  become: yes
  become_user: root
  vars:
    kivy_version: 1.9.1
    cython_version: 0.23
    venv_path: /home/{{ ansible_ssh_user }}/venv34
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Aptitude safe-upgrade
    apt: upgrade=safe

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    with_items:
      - python3-pip
      - build-essential
      - git
      - python3
      - python3-dev
      - libav-tools
      - libjpeg-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - zlib1g-dev

  - name: Upgrade pip, virtualenv, setuptools
    pip:
      name={{ item }}
      state=latest
    with_items:
      - pip
      - virtualenv
      - setuptools

  - name: Create virtualenv
    become: no
    command: virtualenv {{ venv_path }} -p python3
    args:
      creates: "{{ venv_path }}"

  - name: Install Cython in virtualenv
    become: no
    pip:
      name=Cython
      version={{ cython_version }}
      state=present
      virtualenv="{{ venv_path }}"

  - name: Install kivy in virtualenv
    become: no
    pip:
      name=kivy
      version={{ kivy_version }}
      state=present
      virtualenv="{{ venv_path }}"

  # looks like pillow is not always needed, but travis won't work without.
  - name: Install pillow in virtualenv
    become: no
    pip:
      name=pillow
      state=latest
      virtualenv="{{ venv_path }}"
