---
- hosts: all
  become: yes
  remote_user: root
  vars:
    kivy_version: 1.9.1
    cython_version: 0.23
    venv_path: /home/{{ ansible_ssh_user }}/venv27
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Aptitude safe-upgrade
    apt: upgrade=safe

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    with_items:
      - python-pip
      - build-essential
      - git
      - python
      - python-dev
      - libav-tools
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - zlib1g-dev

  - name: Upgrade pip, virtualenv, setuptools
    pip:
      name={{ item }}
      state=latest
    with_items:
      - pip
      - virtualenv
      - setuptools

  - name: Create virtualenv
    become: no
    command: virtualenv {{ venv_path }} -p python2.7
    args:
      creates: "{{ venv_path }}"

  - name: Install Cython in virtualenv
    become: no
    pip:
      name=Cython
      version={{ cython_version }}
      state=present
      virtualenv="{{ venv_path }}"

  - name: Install kivy in virtualenv
    become: no
    pip:
      name=kivy
      version={{ kivy_version }}
      state=present
      virtualenv="{{ venv_path }}"
