---
# This ansible-playbook does setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -k setup-raspi-playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Update system
    apt: upgrade=safe update_cache=yes
  - name: Rotate screen by 180°
    lineinfile: dest=/boot/config.txt line="lcd_rotate=2"
