---
# This ansible-playbook does SSH setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -k setup_ssh_playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  vars:
    - repo_path: /home/{{ ansible_ssh_user }}/waeup.identifier
    # a unique and memorizable name
    - device_id: "test-raspi1"

  handlers:
  - name: "restart sshd"
    service:
      name="ssh"
      enabled=yes
      state=restarted

  tasks:
  - name: Create SSH key, type ed25519
    user:
      name: "{{ ansible_ssh_user }}"
      generate_ssh_key: yes
      ssh_key_type: "ed25519"
      ssh_key_comment: "{{ ansible_ssh_user }}@{{ device_id }}"

  - name: "sshd_config - disable weak keys"
    lineinfile:
      dest=/etc/ssh/sshd_config
      backrefs=yes
      line={{ item.line }}
      regexp={{ item.regexp }}
    with_items:
      - { regexp: '^HostKey /etc/ssh/ssh_host_dsa_key',
          line: '# HostKey /etc/ssh/ssh_host_dsa_key' }
      - { regexp: '^HostKey /etc/ssh/ssh_host_ecdsa_key',
          line: '# HostKey /etc/ssh/ssh_host_ecdsa_key' }
    notify: "restart sshd"

  - name: "sshd_config - set key bits to 4096"
    lineinfile:
      dest=/etc/ssh/sshd_config
      backrefs=yes
      line='ServerKeyBits 4096'
      regexp='^ServerKeyBits 1024'
      state=present
    notify: "restart sshd"

  - name: "sshd_config - set secure ciphers from bettercrypto.org"
    lineinfile:
      dest=/etc/ssh/sshd_config
      line='Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr'
      state=present
    notify: "restart sshd"

  - name: "sshd_config - set secure MACs from bettercrypto.org"
    lineinfile:
      dest=/etc/ssh/sshd_config
      line='MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
      state=present
    notify: "restart sshd"
