---
# This ansible-playbook does setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -u pi -e 'device_id=myraspi_01 reverse_ssh_host=192.168.42.42 reverse_ssh_port=22001' -k setup_raspi_playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  vars:
    - repo_path: /home/{{ ansible_ssh_user }}/waeup.identifier
    - device_id: "test-raspi1"
    - reverse_ssh_host: "192.168.23.23"
    - reverse_ssh_port: "22001"
    - set_password: true
    - new_password: "fading-remedy-pony"
    - remove_bloatware: true

  handlers:
  - name: restart lxpanel
    become: false
    shell: DISPLAY=":0.0" lxpanelctl restart

  - name: restart lightdm
    become: true
    service:
        name: lightdm
        state: restarted

  tasks:
  - name: Update system
    become: true
    apt: upgrade=safe update_cache=yes

  - name: Remove large packages not needed
    become: true
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - "wolfram-engine"
      - "libreoffice*"
    when: remove_bloatware == true

  - name: Rotate screen by 180°
    become: true
    lineinfile: dest=/boot/config.txt line="lcd_rotate=2"

  - name: Disable client-wise LC settings with SSH
    become: true
    lineinfile:
        dest: /etc/ssh/sshd_config
        line: "# AcceptEnv LANG LC_*"
        regexp: "^AcceptEnv (.*)"
        backrefs: yes

  - name: Set new password {{ new_password }}
    become: true
    shell: echo "{{ ansible_ssh_user }}:{{ new_password }}" | chpasswd -s 0 -c SHA512
    when: set_password == true

  - name: Install git
    become: true
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - git

  - name: Clone waeup.identifier git repository
    become: false
    git:
        repo: https://github.com/WAeUP/waeup.identifier
        dest: "{{ repo_path }}"
        update: yes

  - name: Ensure $HOME/.kivy/ dir exists
    become: false
    file: path=/home/{{ ansible_ssh_user }}/.kivy state=directory

  - name: Copy kivy config skeleton
    become: false
    copy: src=config.ini.tmpl force=no dest=/home/{{ ansible_ssh_user }}/.kivy/config.ini

  # this setting is for official raspi touchscreen.
  - name: Tweak kivy mtdev config.ini setting
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "mtdev_%(name)s"
        value: "probesysfs,provider=mtdev"

  # this setting is for official raspi touchscreen
  - name: Remove any hid_%(name)s setting in kivy config.ini
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "hid_%(name)s"
        state: absent

  - name: Create desktop entry for waeup.identifier
    become: false
    copy:
        src: "waeup-identifier.desktop.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/Desktop/waeup-identifier.desktop"
        force: yes

  - name: Create menu entry for waeup.identifier
    become: false
    copy:
        src: "waeup-identifier.desktop.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/.local/share/applications/waeup-identifier.desktop"
        force: yes
    notify: restart lxpanel

  - name: Set standard background
    become: false
    copy:
        src: "desktop-items-0.conf.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/.config/pcmanfm/LXDE-pi/desktop-items-0.conf"
        force: yes
    notify: restart lightdm

  #
  # Remote maintenance: prepare reverse ssh connection
  #
  - name: Create SSH key for ansible user, type ed25519
    user:
      name: "{{ ansible_ssh_user }}"
      generate_ssh_key: yes
      ssh_key_type: "ed25519"
      ssh_key_comment: "{{ ansible_ssh_user }}@{{ device_id }}:{{ reverse_ssh_port }}"

  - name: Copy generated ed25519 SSH key over to local machine
    fetch:
        src: "/home/{{ ansible_ssh_user }}/.ssh/id_ed25519.pub"
        dest: "keys/{{ device_id }}"

  - name: Install reverse SSH launcher
    become: false
    copy:
        src: "start_reverse_ssh.sh"
        dest: "/home/{{ ansible_ssh_user }}/start_reverse_ssh.sh"
        force: no
        mode: 0740

  - name: Set remote reverse SSH host
    become: false
    lineinfile:
        dest: "/home/{{ ansible_ssh_user }}/start_reverse_ssh.sh"
        line: "REMOTE_HOST={{ reverse_ssh_host }}"
        regexp: "^REMOTE_HOST="

  - name: Set remote reverse SSH port
    become: false
    lineinfile:
        dest: "/home/{{ ansible_ssh_user }}/start_reverse_ssh.sh"
        line: "REVERSE_PORT={{ reverse_ssh_port }}"
        regexp: "^REVERSE_PORT="

  - name: Create desktop entry for reverse-ssh starter
    become: false
    copy:
        src: "start_reverse_ssh.desktop.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/Desktop/start_reverse_ssh.desktop"
        force: yes

  - name: Create menu entry for reverse-ssh starter
    become: false
    copy:
        src: "start_reverse_ssh.desktop.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/.local/share/applications/start_reverse_ssh.desktop"
        force: yes
    notify: restart lxpanel

- include: setup_ssh_playbook.yml
