---
# This ansible-playbook does setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -k setup_raspi_playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  vars:
    - repo_path: /home/{{ ansible_ssh_user }}/waeup.identifier

  handlers:
  - name: "restart sshd"
    service:
      name="ssh"
      enabled=yes
      state=restarted

  tasks:
  - name: Update system
    apt: upgrade=safe update_cache=yes

  - name: Rotate screen by 180°
    lineinfile: dest=/boot/config.txt line="lcd_rotate=2"

  - name: Disable client-wise LC settings with SSH
    lineinfile:
        dest: /etc/ssh/sshd_config
        line: "# AcceptEnv LANG LC_*"
        regexp: "^AcceptEnv (.*)"
        backrefs: yes

  - name: Install git
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - git

  - name: Clone waeup.identifier git repository
    become: false
    git:
        repo: https://github.com/WAeUP/waeup.identifier
        dest: "{{ repo_path }}"
        update: yes

  - name: Ensure $HOME/.kivy/ dir exists
    become: false
    file: path=/home/{{ ansible_ssh_user }}/.kivy state=directory

  - name: Copy kivy config skeleton
    become: false
    copy: src=config.ini.tmpl force=no dest=/home/{{ ansible_ssh_user }}/.kivy/config.ini

  # this setting is for official raspi touchscreen.
  - name: Tweak kivy mtdev config.ini setting
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "mtdev_%(name)s"
        value: "probesysfs,provider=mtdev"

  # this setting is for official raspi touchscreen.
  - name: Tweak kivy hid config.ini setting
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "hid_%(name)s"
        value: "probesysfs,provider=hidinput"

  - name: Create desktop entry
    become: false
    copy:
        src: "waeup-identifier.desktop.tmpl"
        dest: "/home/pi/Desktop/waeup-identifier.desktop"
        force: yes

  - name: "sshd_config - disable weak keys"
    lineinfile:
      dest=/etc/ssh/sshd_config
      backrefs=yes
      line={{ item.line }}
      regexp={{ item.regexp }}
    with_items:
      - { regexp: '^HostKey /etc/ssh/ssh_host_dsa_key',
          line: '# HostKey /etc/ssh/ssh_host_dsa_key' }
      - { regexp: '^HostKey /etc/ssh/ssh_host_ecdsa_key',
          line: '# HostKey /etc/ssh/ssh_host_ecdsa_key' }
    notify: "restart sshd"

  - name: "sshd_config - set key bits to 4096"
    lineinfile:
      dest=/etc/ssh/sshd_config
      backrefs=yes
      line='ServerKeyBits 4096'
      regexp='^ServerKeyBits 1024'
      state=present
    notify: "restart sshd"

  - name: "sshd_config - set secure ciphers from bettercrypto.org"
    lineinfile:
      dest=/etc/ssh/sshd_config
      line='Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr'
      state=present
    notify: "restart sshd"

  - name: "sshd_config - set secure MACs from bettercrypto.org"
    lineinfile:
      dest=/etc/ssh/sshd_config
      line='MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
      state=present
    notify: "restart sshd"
