---
# This ansible-playbook does setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -u pi -e 'device_id=myraspi_01' -k setup_raspi_playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  vars:
    - repo_path: /home/{{ ansible_ssh_user }}/waeup.identifier
    - device_id: "test-raspi1"

  tasks:
  - name: Update system
    become: true
    apt: upgrade=safe update_cache=yes

  - name: Rotate screen by 180°
    become: true
    lineinfile: dest=/boot/config.txt line="lcd_rotate=2"

  - name: Disable client-wise LC settings with SSH
    become: true
    lineinfile:
        dest: /etc/ssh/sshd_config
        line: "# AcceptEnv LANG LC_*"
        regexp: "^AcceptEnv (.*)"
        backrefs: yes

  - name: Install git
    become: true
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - git

  - name: Clone waeup.identifier git repository
    become: false
    git:
        repo: https://github.com/WAeUP/waeup.identifier
        dest: "{{ repo_path }}"
        update: yes

  - name: Ensure $HOME/.kivy/ dir exists
    become: false
    file: path=/home/{{ ansible_ssh_user }}/.kivy state=directory

  - name: Copy kivy config skeleton
    become: false
    copy: src=config.ini.tmpl force=no dest=/home/{{ ansible_ssh_user }}/.kivy/config.ini

  # this setting is for official raspi touchscreen.
  - name: Tweak kivy mtdev config.ini setting
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "mtdev_%(name)s"
        value: "probesysfs,provider=mtdev"

  # this setting is for official raspi touchscreen.
  - name: Tweak kivy hid config.ini setting
    become: false
    ini_file:
        dest: "/home/{{ ansible_ssh_user }}/.kivy/config.ini"
        section: "input"
        option: "hid_%(name)s"
        value: "probesysfs,provider=hidinput"

  - name: Create desktop entry
    become: false
    copy:
        src: "waeup-identifier.desktop.tmpl"
        dest: "/home/{{ ansible_ssh_user }}/Desktop/waeup-identifier.desktop"
        force: yes

  - name: Install reverse SSH launcher
    become: false
    copy:
        src: "start_reverse_ssh.sh"
        dest: "/home/{{ ansible_ssh_user }}/start_reverse_ssh.sh"
        force: no

- include: setup_ssh_playbook.yml
