---
# This ansible-playbook prepares a maintenance server
# for connections from client Raspberry pis.
#
# Sample:
#
#   $ ansible-playbook -u <USERNAME-ON-SERVER> -i <SERVER-IP>, -k setup_maintbox_playbook.yml
#
- hosts: all
  become: true
  become_user: root
  vars:
    # Username, used only for reverse SSH connections from raspis.
    - maint_user: "reverse"

  handlers:
  - name: "restart sshd"
    service:
      name="ssh"
      enabled=yes
      state=restarted

  tasks:
  - name: Create system user
    user:
      name: "{{ maint_user }}"
      shell: "/bin/false"
      system: yes
      state: present

  - name: Restrict permissions for "{{ maint_user }}" in sshd_config
    blockinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      marker: "# {mark} ANSIBLE MANAGED BLOCK REVERSE_SSH"
      block: |
        Match User {{ maint_user }}
          AllowTcpForwarding yes
          X11Forwarding no
          #PermitTunnel no
          #GatewayPorts no
          AllowAgentForwarding no
          #PermitOpen localhost:62222
          ForceCommand /bin/echo 'This account can only be used for reverse tunneling'
          PasswordAuthentication no
        Match all
    notify: restart sshd

