---
# This ansible-playbook does setup of a
# Raspberry pi running waeup.identifier.
#
# Sample:
#
#   $ ansible-playbook -i hosts -k setup-raspi-playbook.yml
#
# Make sure, that the IP in `hosts` is the real raspberry-pi.
#
- hosts: all
  become: true
  become_user: root
  vars:
    - repo_path: /home/{{ ansible_ssh_user }}/waeup.identifier
  tasks:
  - name: Update system
    apt: upgrade=safe update_cache=yes

  - name: Rotate screen by 180°
    lineinfile: dest=/boot/config.txt line="lcd_rotate=2"

  - name: Install git
    package:
      name={{ item }}
      state=present
    with_items:
      - git

  - name: Clone waeup.identifier git repository
    become: false
    git: repo=https://github.com/WAeUP/waeup.identifier
         dest="{{ repo_path }}"
         update=no
